# Use the offical Golang image to create a build artifact.
# This is based on Debian and sets the GOPATH to /go.
# https://hub.docker.com/_/golang
FROM golang:1.18 as builder

# Copy local code to the container image.
WORKDIR /go/app
COPY . .

CMD [ "executable" ]
