// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package pgdb

import (
	"context"
)

const getTodo = `-- name: GetTodo :one
SELECT id, name, bio FROM todo
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.queryRow(ctx, q.getTodoStmt, getTodo, id)
	var i Todo
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
