// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package pgdb

import (
	"context"
)

type Querier interface {
	GetTodo(ctx context.Context, id int64) (Todo, error)
}

var _ Querier = (*Queries)(nil)
